### ISSUE TITLE
error https://github.com/Daniel-KM/Omeka-S-module-BulkImport#installation

### ISSUE THREAD

**Issue by clamattu** [Daniel-KM/Omeka-S-module-BulkImport#1]
From the source and for development
If the module was installed from the source, rename the name of the folder of the module to BulkImport.

i think "composer install" is missed in installation description. The installation failed with the error 

[php7:error] [pid 14296] [client x.x.x.x:39168] PHP Fatal error:  require_once(): Failed opening required '/opt/omeka-s/modules/BulkImport/vendor/autoload.php' (include_path='.:
/usr/share/pear:/usr/share/php') in /opt/omeka-s/modules/BulkImport/Module.php on line 23, referer: https://<mysite>/omeka-s/admin/module

**Comment by Daniel-KM** [comment]
Indeed, i'll add it in next version in a few days. 
For info, the next version is able to fetch a whole Omeka S site.

**Comment by Daniel-KM** [comment]
Fixed.
