### ISSUE TITLE
Import de fichier CSv avec Bulk Import

### ISSUE THREAD

**Issue by carolinekoudoroparfait** [Daniel-KM/Omeka-S-module-BulkImport#2]
Bonjour, 

Chaque fois que j'essaie de télécharger un fichier .CSV,  Omeka S me retourne cette erreur  : 
File "bulkimport_itemset_natiflibreO.csv" has media type   "application/vnd.ms-excel", not "text/csv". 

Pourtant mon fichier est bien un .csv encodé UTF8, créé sous Libre office et j'entre bien les bons arguments pour : delimiter, enclosure, escape et séparateur de valeurs multiples

Avez-vous une idée de comment résoudre ce problème, doit-on manipuler le code ?

J'utilise aussi le module CSV, néanmoins je suis intéressée par votre retour quant à ce problème de format de fichier.  
Je vous remercie d'avance,
Cordialement 
CP

**Comment by Daniel-KM** [comment]
Bonjour,
Si vous utilisez libreoffice, le mieux est de le sauvegarder au format standard (ods  / OpenDocument spreadsheet). 
Il faudrait avoir le fichier exemple ou au moins des informations sur le serveur web (serveur windows ?).

**Comment by Daniel-KM** [comment]
Le mieux pour avoir le bon format de fichier est d'utiliser un fichier exporté avec [Bulk Export](https://github.com/Daniel-KM/Omeka-S-module-BulkExport).

**Comment by Daniel-KM** [comment]
C'est un problème lié à la configuration du serveur ou de php, qui détermine les types de fichiers.
