### ISSUE TITLE
Erreur lors de l'importation d'une autre base Omeka S

### ISSUE THREAD

**Issue by fabienbp** [Daniel-KM/Omeka-S-module-BulkImport#3]
Bonjour, J'essaie d'importer les contenus d'un Omeka S dans un nouveau Omeka S. Les modules du premier sont tous installés dans le second. J'obtiens à chaque fois l'erreur suivante (fichier ci-joint avec le journal complet). Auriez-vous une idée de ce qui bloque ? Merci.

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14' for key 'UNIQ_2AF5A5C5CC5DB90' in /home/magnagre/public_html/a/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88

[Error.pdf](https://github.com/Daniel-KM/Omeka-S-module-BulkImport/files/5150709/Error.pdf)

**Comment by Daniel-KM** [comment]
Bonjour,
Il y a un problème lors de l'import des assets. Quand j'ai créé le module, j'avais simpliqué pour les assets pensant qu'il n'y aurait pas de problème avec. Il y a un doublon avec l'asset n° 14, qui existe peut-être déjà. Dans l'immédiat, il est plus simple de purger la table des assets directement dans la base, sinon de supprimer les ligne dans le code : https://github.com/Daniel-KM/Omeka-S-module-BulkImport/blob/master/src/Processor/OmekaSProcessor.php#L953 et https://github.com/Daniel-KM/Omeka-S-module-BulkImport/blob/master/src/Processor/OmekaSProcessor.php#L377
A ce propos, avez-vous une bonne traduction pour assets pour mettre dans la prochaine version ?

**Comment by Daniel-KM** [comment]
Bonjour,
Il y a un problème lors de l'import des assets. Quand j'ai créé le module, j'avais simplifié pour les assets pensant qu'il n'y aurait pas de problème avec. Il y a un doublon avec l'asset n° 14, qui existe peut-être déjà. Dans l'immédiat, il est plus simple de purger la table des assets directement dans la base, sinon de supprimer les lignes dans le code : https://github.com/Daniel-KM/Omeka-S-module-BulkImport/blob/master/src/Processor/OmekaSProcessor.php#L953 et https://github.com/Daniel-KM/Omeka-S-module-BulkImport/blob/master/src/Processor/OmekaSProcessor.php#L377
A ce propos, avez-vous une bonne traduction pour assets pour mettre dans la prochaine version ?

**Comment by Daniel-KM** [comment]
J'ai mis la version 3.0.19.1 qui permet de ne pas importer les assets via une option lors de l'import.

**Comment by fabienbp** [comment]
Bonjour, 
Merci de vos réponses. J'ai essayé d'intsaller la version 3.0.19.1, mais lorsque je clique sur "installer" dans la liste des modules, cela fait planter Omeka et je n'ai plus qu'un écran blanc jusqu'à ce que je supprime le dossier sur mon serveur. Par ailleurs je ne suis pas tout à fait sûr des lignes à supprimer dans le code ou de comment purger les assets.

**Comment by fabienbp** [comment]
J'ai trouvé les lignes de code à enlever. En revanche l'install de la version .1 bugue toujours, je suis reparti de la version précédente. Personnellement je pense qu'il vaut mieux laisser "assets" vu que c'est ce terme qui apparait dans le code. Le problème est que lorsque l'on recherche "assets Omeka", on trouve cette page qui ne parle pas de la même chose : https://omeka.org/s/docs/user-manual/content/items/

**Comment by Daniel-KM** [comment]
J'ai fait une mise à jour du module (3.0.20). Je pense que c'est résolu.
