### ISSUE TITLE
Box/Spout version updated, but error still shown.

### ISSUE THREAD

**Issue by yakumox** [Daniel-KM/Omeka-S-module-BulkImport#4]
I had an error when install from admin.
> The dependency Box/Spout version should be >= 3.0. See readme.

Amazon Linux2
php 7.4
Box/Spout 3.1

On Module.php, box/spout version checked by `class_exists` function.
But it might be that ReaderFactory Class was moved to another place?
https://github.com/box/spout/blob/master/src/Spout/Reader/Common/Creator/ReaderFactory.php

Regards.

**Comment by Daniel-KM** [comment]
There is a collision with the module CSV Import that uses the same dependency ; you need to use the [patch](https://github.com/omeka-s-modules/CSVImport/pull/182) here or use my CSV Import temp fork that includes it.

**Comment by Daniel-KM** [comment]
Or just disable CsvImport when you use BulkImport.

**Comment by yakumox** [comment]
I tried just disable CsvImport, but error still shown.
Next, tried uninstalling CsvImport module, then succeed.
Thank you for your support!

**Comment by Daniel-KM** [comment]
I pushed a fix in order to use the module with the unpatched CSV Import. The release will be built next week.
