### ISSUE TITLE
function getAssetId in ResourceProcessor.php in version 3.4.56

### ISSUE THREAD

**Issue by sorger-c** [Daniel-KM/Omeka-S-module-BulkImport#6]
I am new to Omeka S and started by trying to bulk import assets, item-sets and items. Thank you for your module! It is very helpful. 

I noticed the following. When importing item sets, I used asset ids (as numeric values) to specify the thumbnails of the item sets. It turns out that this causes an error on line 1547 in the ResourceProcessor.php file, as follows

    Fatal error: Uncaught Error: Call to undefined method Omeka\Api\Manager::searchOne() in  /var/www/html/modules/BulkImport/src/Processor/ResourceProcessor.php:1547
    Stack trace:
    #0 /var/www/html/modules/BulkImport/src/Processor/ResourceProcessor.php(504): BulkImport\Processor\ResourceProcessor->getAssetId(1)
    #1 /var/www/html/modules/BulkImport/src/Processor/ResourceProcessor.php(343): BulkImport\Processor\ResourceProcessor->fillResourceSingleEntities(Object(ArrayObject), Array)
    #2 /var/www/html/modules/BulkImport/src/Processor/AbstractResourceProcessor.php(380): BulkImport\Processor\ResourceProcessor->fillResourceFields(Object(ArrayObject), Array)
    #3 /var/www/html/modules/BulkImport/src/Job/ImportTrait.php(922): BulkImport\Processor\AbstractResourceProcessor->fillResource(Array, 1)
    #4 /var/www/html/modules/BulkImport/src/Job/ImportTrait.php(553): BulkImport\Job\Import->processEntry(Object(BulkImport\Entry\SpreadsheetEntry))
    #5 /var/www/html/modules/BulkImport/src/Job/ImportTrait.php(343): BulkImport\Job\Import->prepareListOfIdentifiers()
    #6 /var/www/html/modules/BulkImport/src/Job/Import.php(151): BulkImport\Job\Import->process()
    #7 /var/www/html/application/src/Job/DispatchStrategy/Synchronous.php(34): BulkImport\Job\Import->perform()
    #8 /var/www/html/modules/Log/src/Job/Dispatcher.php(82): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
    #9 /var/www/html/application/data/scripts/perform-job.php(66): Log\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Log\Job\DispatchStrategy\Synchronous))
    #10 {main}
    thrown
    in /var/www/html/modules/BulkImport/src/Processor/ResourceProcessor.php on line 1547

After commenting out the call to searchOne, the import worked fine.

**Comment by Daniel-KM** [comment]
Thanks, it is fixed in version 3.4.57.
